### ISSUE TITLE
Add and remove products

### ISSUE THREAD

**Issue by davidlopezre** [Dlolpez/YZA_PoS_Android_Tablet#1]

**Comment by dalzymendoza** [comment]
Still missing restricted forms (ie possible to add a property value to a product from a property of a different category)

**Comment by dalzymendoza** [comment]
* Implemented nested creation of adding products and product categories
* Still missing validation on product properties to be of the right product category

**Comment by dalzymendoza** [comment]
* Validation for product properties added
